name: light_curve_app
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

#  flutter pub run build_runner watch --delete-conflicting-outputs

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  
  bottom_navy_bar: ^6.0.0
  built_collection: ^5.1.0
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  date_format: ^2.0.2
  flash: ^2.0.1
  flutter:
    sdk: flutter
    
  flutter_redux: ^0.8.2
  flutter_slidable: ^0.6.0

  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.1
  redux: ^5.0.0 
  redux_epics: ^0.15.0
  rxdart: ^0.26.0
  shimmer: ^2.0.0
  url_launcher: ^6.0.9
  
  video_thumbnail: ^0.4.3 

  open_file: ^3.2.1
  file_picker: ^4.0.3

  flutter_svg: ^0.22.0
  video_player: ^2.2.5

  google_sign_in: ^5.0.4
  firebase_storage: ^10.0.3
  cloud_firestore: "^2.4.0"
  firebase_core: "^1.4.0"
  firebase_auth: "^3.0.1"  

dev_dependencies:
  build_runner: ^2.0.5
  flutter_launcher_icons: ^0.9.0 
  flutter_test:
    sdk: flutter

  freezed: ^0.14.2
  json_serializable: ^4.1.3
  lint: ^1.3.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
